#!/bin/bash

die () {
  echo "$@"
  exit 1
}

# Try to remove xt_group and x_tables
# but they may be in use
modprobe -r xt_cgroup || \
  die "Failed to remove xt_cgroup module"
modprobe -r x_tables || \
  die "Failed to remove x_tables"

